services:
  - type: web
    name: vedhika-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    rootDir: event-frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html